{
 "title": "IoT Final Project",
 "description": "1. To show real-time status of door lock\n2. To show unlock events",
 "time": { "from": "now-1s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Door Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"door_status\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == 1 then \"OPEN\" else \"CLOSED\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Door Activity Log (0 = Unlock ; 1 = Lock)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"authentication_log\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: string(v: r._value)\r\n  }))\r\n  |> pivot(\r\n      rowKey: [\"_time\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"door_id\", \"method\", \"action\", \"status\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n"
    }
   ]
  },
  {
   "title": "Lock Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"lock_status\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Door Alert History",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"door_alert\"\r\n  )\r\n  |> pivot(\r\n    rowKey: [\"_time\"],\r\n    columnKey: [\"_field\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"door_id\", \"message\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n"
    }
   ]
  }
 ]
}